# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.

[[constraint]]
  name = "github.com/boombuler/barcode"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/image"

[prune]
  go-tests = true
  unused-packages = true
